---
# General AWS Settings

aws_application_name: myapp
aws_region: us-east-1


# Database Specific Settings

# Application Database
db_admin_password: password
db_admin_username: dbadmin
db_instance_name: "{{ aws_application_name }}-db"

# Database security group
db_security_group_name: "{{ aws_application_name }}-db-group"
