# NGINX

nginx_site_conf_name: team-manager-api.conf
nginx_site_root: /var/www/team-manager-api
nginx_socket: 'http://{{ gunicorn_socket_unix }}'

nginx_site_servers:
  - name: api.mydiscteam.com
    listen: 80
    extra_params: |
          location = /favicon.ico {
            access_log off;
            root {{ django_static_root }}/images;
          }

          location /media/ {
            alias {{ django_media_root }}/;
          }

          location /static/ {
            alias {{ django_static_root }}/;
          }

          location / {
            include proxy_params;
            proxy_pass {{ nginx_socket }};
          }



# Django Application

app_name: team-manager-api
app_package: team_api

app_repo: 'https://github.com/cdriehuys/team-manager-api'

app_required_packages:
  - libpq-dev
  - python3
  - python3-dev
  - python3-pip

django_requirements: "{{ django_project }}/requirements/prod.txt"
django_manage_commands:
  - 'collectstatic --noinput'

django_allowed_hosts:
  - api.mydiscteam.com
django_secret_key: "{{ vault_django_secret_key }}"
django_media_root: "{{ nginx_site_root }}/media"
django_static_root: "{{ nginx_site_root }}/static"

django_databases:
  default:
    ENGINE: django.db.backends.postgresql_psycopg2
    NAME: "{{ db_name }}"
    USER: "{{ db_username }}"
    PASSWORD: "{{ db_password }}"
    HOST: "{{ db_instance.instance.endpoint }}"
    PORT: "{{ db_port }}"
