---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - env_vars/base.yml

  roles:
    - provision-database
    - create-ami-builder

- name: Configure instance to create AMI
  hosts: amibuilder
  gather_facts: false

  become: yes
  become_user: root
  remote_user: ubuntu

  vars_files:
    - env_vars/base.yml

  pre_tasks:
    - name: Install python 2
      become: yes
      become_user: root
      remote_user: ubuntu
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""

  roles:
    - cdriehuys.django-app
    - cdriehuys.nginx

- name: Finalize AMI
  hosts: localhost
  connection: local

  vars_files:
    - env_vars/base.yml

  roles:
    - finalize-ami
