# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_admin',
            field=models.BooleanField(default=False, help_text="Admin members are allowed to edit the team's information, as well as change player info.", verbose_name='is admin'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Coach'), (1, 'Player')], default=1, verbose_name='member type'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
