# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_invite_url_endpoints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvite',
            unique_together=set([('email', 'team')]),
        ),
    ]
