# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0006_unique_team_invites'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set([('team', 'user')]),
        ),
    ]
